### ISSUE TITLE
StopIteration while training

### ISSUE THREAD

**Issue by hanjw123** [610265158/DSFD-tensorflow#4]
[2019-06-20 15:29:11,657] [INFO] epoch 0: iter 530, total_loss=25.726513 reg_loss=6.941636 cla_loss=4.874024 l2_loss=2.409790 learning rate =5.000000e-04 (25.5 examples/sec; 0.235 sec/batch) fetch data time = 0.339277run time = 0.470284 
Traceback (most recent call last):
  File "train.py", line 8, in <module>
    trainner.train()
  File "/mapbar/data/home/hanjw/face_detection/base_trainer/net_work.py", line 484, in train
    self.train_loop()
  File "/mapbar/data/home/hanjw/face_detection/base_trainer/net_work.py", line 349, in train_loop
    self._train(self.train_ds,epoch)
  File "/mapbar/data/home/hanjw/face_detection/base_trainer/net_work.py", line 405, in _train
    examples = next(train_ds)
StopIteration

**Comment by hanjw123** [comment]
resolved，I mistake the dataset size.
